#!/bin/bash

# List the usernames who have only unsuccessful attempts stored in the handin-server

if [ $# -ne 1 ]; then
  echo "List the usernames who have only unsuccessful attempts stored in the handin-server"
  echo ""
  echo "Usage: attempts-only assignment"
  echo "Example: attempts-only a2"
  exit
fi

assignment=$1

faculty=(menzel schackb jaiguerr metcalka cfactora kmbitner projanen mdhook eeleonha jenlipso cylimill crschmit dtzvetko daaasbu ysieweni mthyde)
# Helper function for searching within arrays
# returns 0 for yes, 1 for no
# Usage: elementIn element "${array[@]}"
elementIn () {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}

usernames="/u/c211/spring15/handin-server/$assignment"

for path_username in $usernames/*
do
    username=${path_username##*/}
    elementIn $username "${faculty[@]}"
    if [ $? == 1 ]; then
	while read item; do
	    # the following command will return 1 if no results
	    # which means this user had no successful submissions
	    (ls $usernames/$username | grep SUCCESS > /dev/null)
	    if [ $? == 1 ]; then
		echo $username
	    fi
	done < <(ls $usernames/$username | grep ATTEMPT)
    fi
done
