#!/bin/bash

# A wrapper for collecting, distributing, and PDFing homework assignments submitted via Dr Racket's handing-server

if [ $# -ne 1 ]; then
  echo ""
  echo "A wrapper for collecting, distributing, and PDFing homework assignments submitted via Dr Racket's handing-server"
  echo
  echo "Usage: collect-and-distribute assignment"
  echo "Example: collect-and-distribute a1"
  exit
fi

assignment=$1

/u/c211/bin/collect $assignment

# If collect failed, do not attempt the distribute
if [ $? -ne 0 ]; then
  echo
  echo "collect failed, will not attempt to distribute"
  echo
  exit $?
fi

/u/c211/bin/distribute $assignment
