#!/bin/bash

# Prints to LH201 all handins for the given assignment and lab section

if [ $# -ne 2 ]; then
  echo ""
  echo "Prints to LH201 all handins for the given assignment and lab section"
  echo "Usage: print201 [assignment] [lab section]"
  echo ""
  exit
fi

/u/c211/bin/print-elsewhere $1 $2 201